### ISSUE TITLE
Security, Scalability, Usability Issues

### ISSUE THREAD

**Issue by jpillora** [TOMODOcom/TOMODOkorz#3]
As the other #1 mentioned, proxying everyone's requests through your own servers by default, is both a huge security concern, in addition to not being scalable. I see that you're using Apache, though what are the specs on that box? What if 1000 devs started using this today on their ajax heavy sites, each along with their 1000 users. It would be slow, or even worse - down, for everyone, 

Also, you'd be proxying cookies too. If user uses this to connect to `abc.com`, then `xyz.com`, `xyz` will recieve all of the cookies created by `abc`. Very bad.

The only real solution is for everyone to run their own proxy. Though since this requires CORS, if they're capable of running their own proxy, then they'd be capable of just adding the necessary CORS headers to their own server.

For a transparent, cross-domain, security conscious, vanilla javascript, CORS-less solution to this, only using static js files, see [XDomain](https://github.com/jpillora/xdomain) (which depends on [XHook](https://github.com/jpillora/xhook)).

**Comment by odedgolan** [comment]
Hi and thank you for the feedback. 

The first thing that is important to understand is that not all traffic is sent to the proxy, just the cross-origin traffic, you can also see it in the code.

Regarding scale, TOMODOkorz is a small side project we needed for TOMODO(tomodo.com) and decided to make available to everyone. We tackle much bigger traffic challenges on TOMODO so I won't be too concerned about that. 

Regarding cookies, when you're making cross-origin request on TOMODOkorz the request in going to korz.tomodo.me/url so cookies to the target domain are not sent, in addition our server code does not pass cookies. 

It's an easy and simple solution that allows you to get external content from any source, don't use it to fetch data from your bank account, use it to fetch data from your favorite blog.

**Comment by jpillora** [comment]
Right, though it's quite common to have an `api.example.com` as the backend for `www.example.com`. In which case all traffic would indeed be sent to the proxy.

Just curious, is `CPython/2.7.3 Linux/3.2.0-38-virtual` cloud hosted? How many instances is it?

I meant if you do a POST `api.example.com/login`, it will return a `Set-Cookie`. Even if you're not forwarding the `Set-Cookie` header, your server is still receiving the contents of the header with possible sensitive information.

That's fine if its just used to retrieve public data, though still, users should opt-in to using your proxy server with instructions on how to set to it yours and the implications of doing so. If someone saw this as a quick drop in replacement for setting up CORS on their own server, they may not realize you're receiving all their users data and set this up in the backend scenario above.

From an adversarial standpoint, this could be a ruse to get people to send you their data, which would be abusing the opensource community. In these NSA-spying-times, one can never be sure. Safest to just do the responsible thing and make it opt-in.
